name: Release
on:
  push:
    tags:
      - '**'
jobs:
  release:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Determine tag
        id: vars
        uses: actions/github-script@v5
        with:
          script: |
            const { GITHUB_REF } = process.env
            const tag = GITHUB_REF.replace('refs/tags/', '')
            console.log(`Got the following tag: ${tag}`)
            return tag
          result-encoding: string

      - name: Setup build tools
        run: |
          sudo apt-get update
          sudo apt-get install build-essential autoconf automake g++ libtool -y

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Setup yarn
        run: npm install -g yarn

      - name: Setup cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-core-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn

      - name: Build artifacts
        run: yarn dist

      - name: Upload artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: ./out/aion.linux-amd64.deb
